// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A DMCA letter generation AI agent.
 *
 * - generateDMCALetter - A function that handles the DMCA letter generation process.
 * - GenerateDMCALetterInput - The input type for the generateDMCALetter function.
 * - GenerateDMCALetterOutput - The return type for the generateDMCALetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDMCALetterInputSchema = z.object({
  mentionTitle: z.string().describe('The title of the infringing content.'),
  mentionUrl: z.string().url().describe('The URL where the infringing content is located.'),
  originalWorkDescription: z.string().describe('A detailed description of the original work that is being infringed upon.'),
  fullName: z.string().describe('Your full name or the name of the copyright holder.'),
  address: z.string().describe('Your address or the address of the copyright holder.'),
  email: z.string().email().describe('Your email address.'),
  phoneNumber: z.string().describe('Your phone number.'),
});
export type GenerateDMCALetterInput = z.infer<typeof GenerateDMCALetterInputSchema>;

const GenerateDMCALetterOutputSchema = z.object({
  dmcaLetter: z.string().describe('A draft of the DMCA takedown notice.'),
});
export type GenerateDMCALetterOutput = z.infer<typeof GenerateDMCALetterOutputSchema>;

export async function generateDMCALetter(input: GenerateDMCALetterInput): Promise<GenerateDMCALetterOutput> {
  return generateDMCALetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDMCALetterPrompt',
  input: {schema: GenerateDMCALetterInputSchema},
  output: {schema: GenerateDMCALetterOutputSchema},
  prompt: `You are an AI assistant specialized in generating DMCA takedown notices.

  Based on the information provided, draft a DMCA letter that can be used to request the removal of infringing content.

  Infringing Content Title: {{{mentionTitle}}}
  Infringing Content URL: {{{mentionUrl}}}
  Original Work Description: {{{originalWorkDescription}}}
  Copyright Holder Name: {{{fullName}}}
  Copyright Holder Address: {{{address}}}
  Copyright Holder Email: {{{email}}}
  Copyright Holder Phone Number: {{{phoneNumber}}}

  DMCA Letter:`,
});

const generateDMCALetterFlow = ai.defineFlow(
  {
    name: 'generateDMCALetterFlow',
    inputSchema: GenerateDMCALetterInputSchema,
    outputSchema: GenerateDMCALetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
